language: ruby
rvm:
  - 2.1
env:
  - OFFLINE_BUILD_FOLDER=intro
install:
  - gem install github-pages
script:
  - echo "Build online version"
  - jekyll build
  - echo "Build offline version"
  - git fetch origin offline
  - mkdir offline
  - cp -r .git offline
  - ( cd offline && git checkout offline )
  - jekyll build --destination "$OFFLINE_BUILD_FOLDER"
deploy:
  provider: script
  script: scripts/deploy-offline-build-branch.sh
  file_glob: true
  on:
    branch: issue-17-offline-support
