sourcecode:
  repository: "https://github.com/CoderDojoPotsdam/CoderDojoPotsdam.github.io/intro"
  root: "https://github.com/CoderDojoPotsdam/intro/blob/master/"
keep_files:
  - offline
local_server: "http://localhost:25444"
